services:
  pythonapp:
    build: ./
    command: sh -c "sleep 10s; python3 ./main.py"
    depends_on:
      - redisdatabase
  redisdatabase:
    image: redis:7.0-alpine
    container_name: rdb
    ports:
      - "6379:6379"
